//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroScrap2000.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroScrap2000.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap donate48 {
            get {
                object obj = ResourceManager.GetObject("donate48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_de {
            get {
                object obj = ResourceManager.GetObject("flag_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_en {
            get {
                object obj = ResourceManager.GetObject("flag_en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_es {
            get {
                object obj = ResourceManager.GetObject("flag_es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_fr {
            get {
                object obj = ResourceManager.GetObject("flag_fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderopen32 {
            get {
                object obj = ResourceManager.GetObject("folderopen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grützesoftware_icon {
            get {
                object obj = ResourceManager.GetObject("grützesoftware_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap joystick_32 {
            get {
                object obj = ResourceManager.GetObject("joystick_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap joystickani {
            get {
                object obj = ResourceManager.GetObject("joystickani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options_32 {
            get {
                object obj = ResourceManager.GetObject("options_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RetroScrap2000_256 {
            get {
                object obj = ResourceManager.GetObject("RetroScrap2000_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_32 {
            get {
                object obj = ResourceManager.GetObject("save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanrom_32 {
            get {
                object obj = ResourceManager.GetObject("scanrom_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screenscraper_banner {
            get {
                object obj = ResourceManager.GetObject("screenscraper_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screenscraper_ico {
            get {
                object obj = ResourceManager.GetObject("screenscraper_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your login and internet connection..
        /// </summary>
        internal static string Txt_Api_Err_CheckInternet {
            get {
                return ResourceManager.GetString("Txt_Api_Err_CheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No response from server..
        /// </summary>
        internal static string Txt_Api_Err_NoResponse {
            get {
                return ResourceManager.GetString("Txt_Api_Err_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed or user information is missing..
        /// </summary>
        internal static string Txt_Api_Err_UserFail {
            get {
                return ResourceManager.GetString("Txt_Api_Err_UserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Download: {0} KB/s.
        /// </summary>
        internal static string Txt_Api_SsUser_DownloadKBS {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_DownloadKBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_LastLogin {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_Level {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Threads: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_MaxThreads {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_Name {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_Region {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests per Day: {0}/{1} ({2}%).
        /// </summary>
        internal static string Txt_Api_SsUser_RequestPerDay {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_RequestPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits: {0}.
        /// </summary>
        internal static string Txt_Api_SsUser_Visits {
            get {
                return ResourceManager.GetString("Txt_Api_SsUser_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Txt_Column_ScrapAuto_Message {
            get {
                return ResourceManager.GetString("Txt_Column_ScrapAuto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Txt_Column_ScrapAuto_Time {
            get {
                return ResourceManager.GetString("Txt_Column_ScrapAuto_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Txt_Column_ScrapAuto_Type {
            get {
                return ResourceManager.GetString("Txt_Column_ScrapAuto_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Image for Rom..
        /// </summary>
        internal static string Txt_Dlg_Select_Image {
            get {
                return ResourceManager.GetString("Txt_Dlg_Select_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Video-File for Rom..
        /// </summary>
        internal static string Txt_Dlg_Select_Video {
            get {
                return ResourceManager.GetString("Txt_Dlg_Select_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation has been requested. Please wait..
        /// </summary>
        internal static string Txt_Log_Scrap_CancelRequest {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the data from.
        /// </summary>
        internal static string Txt_Log_Scrap_CheckDataFrom {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_CheckDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap process completed..
        /// </summary>
        internal static string Txt_Log_Scrap_End {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Txt_Log_Scrap_Loading {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for.
        /// </summary>
        internal static string Txt_Log_Scrap_NoDataFoundFor {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_NoDataFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game found..
        /// </summary>
        internal static string Txt_Log_Scrap_NoGameFound {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_NoGameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer is not JSON Format..
        /// </summary>
        internal static string Txt_Log_Scrap_NoJson {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_NoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name provided..
        /// </summary>
        internal static string Txt_Log_Scrap_NoName {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Gamelist.xml....
        /// </summary>
        internal static string Txt_Log_Scrap_SaveGameList {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_SaveGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Gamelist.xml!.
        /// </summary>
        internal static string Txt_Log_Scrap_SaveGamelist_fail {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_SaveGamelist_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamelist.xml successfully saved..
        /// </summary>
        internal static string Txt_Log_Scrap_SaveGamelist_success {
            get {
                return ResourceManager.GetString("Txt_Log_Scrap_SaveGamelist_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language will be fully adopted after a restart. Would you like to restart the application now?.
        /// </summary>
        internal static string Txt_Msg_Opt_Language_Change {
            get {
                return ResourceManager.GetString("Txt_Msg_Opt_Language_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important info for RetroPie users:.
        /// </summary>
        internal static string Txt_Msg_Opt_RetroPie_Info1 {
            get {
                return ResourceManager.GetString("Txt_Msg_Opt_RetroPie_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool creates the gamelist.xml and media files directly in the respective ROM folders. To ensure that EmulationStation can load them correctly, only a small adjustment is required:.
        /// </summary>
        internal static string Txt_Msg_Opt_RetroPie_Info2 {
            get {
                return ResourceManager.GetString("Txt_Msg_Opt_RetroPie_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the main menu in EmulationStation and go to &apos;UI Settings.&apos; Set the option &apos;Parse Gamelists Only&apos; to OFF. After this setting, EmulationStation will display the data created by this tool as usual..
        /// </summary>
        internal static string Txt_Msg_Opt_RetroPie_Info3 {
            get {
                return ResourceManager.GetString("Txt_Msg_Opt_RetroPie_Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the file &apos;{0}&apos; with the associated ROM information really be deleted?.
        /// </summary>
        internal static string Txt_Msg_Qestion_DeleteRom {
            get {
                return ResourceManager.GetString("Txt_Msg_Qestion_DeleteRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid path..
        /// </summary>
        internal static string Txt_Msg_Rom_WrongPath {
            get {
                return ResourceManager.GetString("Txt_Msg_Rom_WrongPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scrap process has failed..
        /// </summary>
        internal static string Txt_Msg_Scrap_Fail {
            get {
                return ResourceManager.GetString("Txt_Msg_Scrap_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found for the Rom..
        /// </summary>
        internal static string Txt_Msg_Scrap_NoDataFound {
            get {
                return ResourceManager.GetString("Txt_Msg_Scrap_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rom selected..
        /// </summary>
        internal static string Txt_Msg_Scrap_NoRom {
            get {
                return ResourceManager.GetString("Txt_Msg_Scrap_NoRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable system could be found for the ROM..
        /// </summary>
        internal static string Txt_Msg_Scrap_NoSystem {
            get {
                return ResourceManager.GetString("Txt_Msg_Scrap_NoSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ROM file could not be determined..
        /// </summary>
        internal static string Txt_Msg_Scrap_WrongRomFile {
            get {
                return ResourceManager.GetString("Txt_Msg_Scrap_WrongRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To fully utilize the application, the username and password for screenscraper.fr must be entered under options..
        /// </summary>
        internal static string Txt_Msg_StartAppNoSsUser {
            get {
                return ResourceManager.GetString("Txt_Msg_StartAppNoSsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available. Update your old version {0} to the new version {1}. Use the link for the download..
        /// </summary>
        internal static string Txt_Msg_UpdateV1toV2 {
            get {
                return ResourceManager.GetString("Txt_Msg_UpdateV1toV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Txt_PleaseWait {
            get {
                return ResourceManager.GetString("Txt_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping {0} ROMs from system.
        /// </summary>
        internal static string Txt_Scrap_Auto_Title_FromSystem {
            get {
                return ResourceManager.GetString("Txt_Scrap_Auto_Title_FromSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing RetroScrap 2000.....
        /// </summary>
        internal static string Txt_Splash_Initializing {
            get {
                return ResourceManager.GetString("Txt_Splash_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Txt_Splash_Loading {
            get {
                return ResourceManager.GetString("Txt_Splash_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Settings....
        /// </summary>
        internal static string Txt_Splash_LoadingSettings {
            get {
                return ResourceManager.GetString("Txt_Splash_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Systems....
        /// </summary>
        internal static string Txt_Splash_LoadingSystems {
            get {
                return ResourceManager.GetString("Txt_Splash_LoadingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Roms loaded..
        /// </summary>
        internal static string Txt_Status_Label_AnzRomsLoad {
            get {
                return ResourceManager.GetString("Txt_Status_Label_AnzRomsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retrosystems are being loaded....
        /// </summary>
        internal static string Txt_Status_Label_ReadRoms {
            get {
                return ResourceManager.GetString("Txt_Status_Label_ReadRoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Roms from {0}....
        /// </summary>
        internal static string Txt_Status_Label_ReadSystem {
            get {
                return ResourceManager.GetString("Txt_Status_Label_ReadSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Txt_Status_Label_Ready {
            get {
                return ResourceManager.GetString("Txt_Status_Label_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rome could not be saved..
        /// </summary>
        internal static string Txt_Status_Label_RomNotSaved {
            get {
                return ResourceManager.GetString("Txt_Status_Label_RomNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom was successfully saved..
        /// </summary>
        internal static string Txt_Status_Label_RomSave {
            get {
                return ResourceManager.GetString("Txt_Status_Label_RomSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online search via screenscraper.fr is running....
        /// </summary>
        internal static string Txt_Status_Label_Scrap_Running {
            get {
                return ResourceManager.GetString("Txt_Status_Label_Scrap_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Txt_System_Manufacturer {
            get {
                return ResourceManager.GetString("Txt_System_Manufacturer", resourceCulture);
            }
        }
    }
}
